import { APIJson } from "./types";

const testJson: APIJson = {
  template_set: {
    code: "DEFAULT",
    id: 1443,
  },
  transaction: null,
  session: {
    name: "fcsid",
    id: "vdjidopcjha75i6be2a7a2ioh5",
  },
  debug: false,
  customer: {
    first_name: "",
    last_name: "",
    email: "",
    type: null,
    id: null,
    token: null,
  },
  shipments: [
    {
      address_id: null,
      address_name: "",
      first_name: "",
      last_name: "",
      company: "",
      phone: "",
      address1: "",
      address2: "",
      city: "",
      region: "",
      postal_code: "",
      country: "US",
      shipping_service_id: null,
      has_shippable_items: false,
      has_live_rate_shippable_items: false,
      shipping_service_options: [],
    },
  ],
  items: [
    {
      id: 5646025,
      name: "test",
      code: "sku123",
      parent_code: "",
      image: null,
      url: null,
      length: null,
      length_unit: "IN",
      width: null,
      height: null,
      weight: 1,
      weight_unit: "LBS",
      quantity: 4,
      quantity_min: 0,
      quantity_max: null,
      base_price: 1,
      price_each: 1,
      price_each_with_tax: 1.1,
      price: 4,
      price_with_tax: 4.4,
      item_category_code: "DEFAULT",
      item_delivery_type: "notshipped",
      delivery_type: "",
      downloadable_id: null,
      downloadable_url: null,
      subscription_frequency: null,
      subscription_start_date: "0000-00-00",
      subscription_next_transaction_date: "0000-00-00",
      subscription_end_date: "0000-00-00",
      expires: null,
      options: [
        {
          id: 4820219,
          name: "color",
          value: "red",
          price_mod: 0,
          weight_mod: 0,
        },
      ],
    },
  ],
  totals: [
    {
      date: null,
      taxes: [
        {
          name: "United States",
          rate: 10,
          amount: 0.4,
          is_included: true,
        },
      ],
      coupons: [],
      gift_cards: [],
      total_line_item_discount: 0,
      total_shipping: 0,
      total_shipping_with_tax: 0,
      total_shipping_value: 4,
      total_tax: 0.4,
      total_item_price: 4,
      total_item_price_with_tax: 4.4,
      total_weight: 4,
      total_weight_shippable: 0,
      total_order: 4.4,
    },
  ],
  billing_address: {
    use_customer_shipping_address: true,
    address_id: null,
    address_name: "",
    first_name: "",
    last_name: "",
    company: "",
    phone: "",
    address1: "",
    address2: "",
    city: "",
    region: "",
    postal_code: "",
    country: "US",
  },
  store: {
    id: 40075,
    name: "Test Store",
    domain: "store-dev-filip",
    logo_url:
      "https://mir-s3-cdn-cf.behance.net/projects/404/093f0626077083.554ea285ad625.jpg",
    website_url: "https://example.com/",
    checkout_url: "https://store-dev-filip.foxycart.test/checkout",
    cancel_and_continue_url: "",
    has_location_dependent_taxes: true,
    has_eligible_gift_cards: true,
    has_eligible_coupons: true,
    supported_payment_cards: [
      "visa",
      "mastercard",
      "discover",
      "amex",
      "dinersclub",
      "maestro",
      "laser",
      "jcb",
      "unionpay",
    ],
  },
  messages: [],
  custom_fields: {
    name: "value",
  },
  format: {
    weight_unit: "LBS",
    locale_code: "de_DE",
    currency_code: "EUR",
    currency_display: "symbol",
    maximum_fraction_digits: 2,
  },
  display: {
    hidden_product_options: [],
    required_form_fields: [
      "billing_first_name",
      "billing_address1",
      "billing_city",
      "billing_postal_code",
      "billing_country",
    ],
    hidden_form_fields: [],
    use_readonly_cart_on_checkout: false,
    use_tax_inclusive_pricing: true,
    secure_data_transfer_consent: "disabled",
    checkout_flow: "default",
    registration: "optional",
  },
  custom_config: [],
  saved_payment_methods: null,
  payment_gateways: [
    {
      type: "securetrading",
      apple_pay: false,
      google_pay: false,
    },
    {
      type: "accept_blue_ach",
      fields: {
        ach_routing_number: "",
        ach_account_number: "",
        ach_name_account: "",
      },
      account_types: ["checking", "savings"],
    },
    {
      type: "adyen_embedded",
      environment: "test",
      client_key: "test_4C526YTVGZF3BEVIKLUWRHU5BMHR6CTN",
      payment_methods_response: {
        paymentMethodsResponse: {
          paymentMethods: [
            {
              brands: [
                "maestro",
                "accel",
                "amex",
                "cup",
                "discover",
                "elo",
                "jcb",
                "maestro_usa",
                "mc",
                "nyce",
                "pulse",
                "star",
                "visa",
              ],
              configuration: {
                merchantId: "000000000321677",
                merchantName: "Foxycart",
              },
              name: "Apple Pay",
              type: "applepay",
            },
            {
              name: "AliPay",
              type: "alipay",
            },
            {
              issuers: [
                {
                  id: "BDO",
                  name: "BDO Internet Banking",
                },
                {
                  id: "BDRE",
                  name: "BDO Retail E-Paymetns",
                },
                {
                  id: "BOG",
                  name: "Test Bank Online",
                },
                {
                  id: "BPIA",
                  name: "BPI Online/Mobile",
                },
                {
                  id: "CBC",
                  name: "Chinabank Online",
                },
                {
                  id: "CBCB",
                  name: "China Bank Online Bills Payment",
                },
                {
                  id: "CBDD",
                  name: "China Bank Online Direct Debit (NEW)",
                },
                {
                  id: "CEBB",
                  name: "Cebuana Lhuillier Rural Bank",
                },
                {
                  id: "DPAY",
                  name: "Dragonpay Prepaid Credits",
                },
                {
                  id: "DPWL",
                  name: "Dragonpay Wallet",
                },
                {
                  id: "EWOB",
                  name: "EastWest Online Banking",
                },
                {
                  id: "INPY",
                  name: "Instapay using any bank/ewallet (NEW)",
                },
                {
                  id: "LBPA",
                  name: "Landbank ATM Online",
                },
                {
                  id: "MAYB",
                  name: "Maybank Online Banking",
                },
                {
                  id: "MBTC",
                  name: "Metrobankdirect",
                },
                {
                  id: "PBCM",
                  name: "PBCom Online Banking",
                },
                {
                  id: "RCDD",
                  name: "RCBC Online Direct Debit (NEW)",
                },
                {
                  id: "SBC",
                  name: "Security Bank Online Bills Payment",
                },
                {
                  id: "UBDD",
                  name: "Unionbank Online Direct Debit (NEW)",
                },
                {
                  id: "UCPB",
                  name: "UCPB Connect/Mobile",
                },
                {
                  id: "VAPT",
                  name: "Vapt Test Bank Online",
                },
              ],
              name: "Online Banking",
              type: "dragonpay_ebanking",
            },
            {
              configuration: {
                merchantId: "50",
                gatewayMerchantId: "FoxycartCOM",
              },
              name: "Google Pay",
              type: "googlepay",
            },
            {
              name: "Paysafecard",
              type: "paysafecard",
            },
            {
              name: "WeChat Pay",
              type: "wechatpayQR",
            },
            {
              name: "WeChat Pay",
              type: "wechatpayWeb",
            },
            {
              name: "Zip",
              type: "zip",
            },
            {
              name: "Zip POS",
              type: "zip_pos",
            },
          ],
        },
        environment: "test",
        clientKey: "test_4C526YTVGZF3BEVIKLUWRHU5BMHR6CTN",
      },
    },
    {
      type: "paypal_platform",
      client_id:
        "Ad-zeePXTAh_S5V8asI4mTho_mONPykDjXR426WdnCFPW5EtdJ-4nRFwZeVBd_KDZlns9n1FaQphAwR4",
    },
    {
      type: "klarna",
      session_id: "ecbabf03-cb8c-6790-aac3-b329d526335c",
      client_token:
        "eyJhbGciOiJSUzI1NiIsImtpZCI6IjgyMzA1ZWJjLWI4MTEtMzYzNy1hYTRjLTY2ZWNhMTg3NGYzZCJ9.eyJzZXNzaW9uX2lkIjoiZWNiYWJmMDMtY2I4Yy02NzkwLWFhYzMtYjMyOWQ1MjYzMzVjIiwiYmFzZV91cmwiOiJodHRwczovL2pzLnBsYXlncm91bmQua2xhcm5hLmNvbS9ldS9rcCIsImxhbmd1YWdlIjoiZW4iLCJwdXJjaGFzZV9jb3VudHJ5IjoiVVMiLCJlbnZpcm9ubWVudCI6InBsYXlncm91bmQiLCJtZXJjaGFudF9uYW1lIjoiWW91ciBidXNpbmVzcyBuYW1lIiwic2Vzc2lvbl90eXBlIjoiUEFZTUVOVFMiLCJjbGllbnRfZXZlbnRfYmFzZV91cmwiOiJodHRwczovL2V1LnBsYXlncm91bmQua2xhcm5hZXZ0LmNvbSIsInNjaGVtZSI6dHJ1ZSwiZXhwZXJpbWVudHMiOlt7Im5hbWUiOiJrcGMtYWJlIiwidmFyaWF0ZSI6InZhcmlhdGUtMSJ9LHsibmFtZSI6ImtwYy1vcGYtdiIsInZhcmlhdGUiOiJ2YXJpYXRlLTEiLCJwYXJhbWV0ZXJzIjp7InYiOiJiZXRhIn19LHsibmFtZSI6ImtwYy1vcGYtZmluYWxpemUtaW4tcG9wdXAiLCJ2YXJpYXRlIjoidmFyaWF0ZS0xIn0seyJuYW1lIjoia3BjLW9zbS13aWRnZXQiLCJ2YXJpYXRlIjoidjEifSx7Im5hbWUiOiJrcGMtcHNlbC00NDI5IiwidmFyaWF0ZSI6ImEifSx7Im5hbWUiOiJrcC1jbGllbnQtb25lLXB1cmNoYXNlLWZsb3ciLCJ2YXJpYXRlIjoidmFyaWF0ZS0xIn0seyJuYW1lIjoia3BjLTFrLXNlcnZpY2UiLCJ2YXJpYXRlIjoidmFyaWF0ZS0xIn0seyJuYW1lIjoia3AtY2xpZW50LXV0b3BpYS1zdGF0aWMtd2lkZ2V0IiwidmFyaWF0ZSI6ImluZGV4IiwicGFyYW1ldGVycyI6eyJkeW5hbWljIjoidHJ1ZSJ9fSx7Im5hbWUiOiJrcC1jbGllbnQtdXRvcGlhLWZsb3ciLCJ2YXJpYXRlIjoidmFyaWF0ZS0xIn0seyJuYW1lIjoia3AtY2xpZW50LXV0b3BpYS1zZGstZmxvdyIsInZhcmlhdGUiOiJ2YXJpYXRlLTEifSx7Im5hbWUiOiJrcC1jbGllbnQtdXRvcGlhLXdlYnZpZXctZmxvdyIsInZhcmlhdGUiOiJ2YXJpYXRlLTEifV0sInJlZ2lvbiI6ImV1Iiwib3JkZXJfYW1vdW50IjoxMTAsIm9mZmVyaW5nX29wdHMiOjAsIm9vIjoiMCIsInZlcnNpb24iOiJ2MS4xMC4wLTE1OTAtZzNlYmMzOTA3In0.SSudk4Ip0dN1yKY4CBeS4HAuKP2sicYo9ipMADtFU1CMF9uw9WIEPj4uU1jaIgWh4f7OkVz32FIEmn7-f8o4UF9x9dPFCgH3S_ie8ZUM0ERRRcVCvXnorD5NRtOLxVEv5-qdOS4P5ENJf-lJM0E4K23Juk3UjQYa4_Noh1R5qx8fA9yXidtLQm-IY7gq8SDmASyFLcjs29C_MUqOKsulThio5iBXJS343tr6ivppmxwYWSVAQOnHF3zAoTP3X7kDaRvhmOF4-RL5yjLdfjo1nq7taakBa7dVVFfCYV7JxW09cFNjoqzWOLkSBoB1KDcaMq08LrHIOvbtsTu_BqQceg",
      payment_method_categories: [],
    },
    {
      type: "sezzle",
      public_key: "sz_pub_ouMoiOF3bXv1XzFJPVeNofnNkwbVZn9n",
    },
    {
      type: "square_up",
      application_id: "sandbox-sq0idb-_tH4zoeEivM7qfzgpNCblA",
      location_id: "38NX2RCKFVJF3",
      environment: "sandbox",
    },
  ],
  express_checkout_options: null,
  language_strings: null,
};
