export type CardPaymentMethod = {
  /** Credit/debit card payment method. */
  type: "card";
  /** Stored card token when the backend exposes it for CSC-only verification. */
  token?: string;
  /** Last 4 digits of the card. */
  last4: string;
  /** Card type (e.g., 'Visa', 'MasterCard'). */
  card_type: string;
  /** Card expiration month. */
  expiration_month: number;
  /** Card expiration year. */
  expiration_year: number;
};

export type PurchaseOrderPaymentMethod = {
  /** Purchase order payment method. */
  type: "purchase_order";
  /** Purchase order number. */
  po_number: string;
};

export type AchPaymentMethod = {
  /** ACH payment method represented by a provider token. */
  type: "ach";
  /** Single-use token generated by hosted fields controller. */
  token?: string;
  /** Last 4 digits of account number when available. */
  last4?: string;
  /** Sanitized issuing bank display name. */
  bank_name?: string;
};

export type StripeConnectPaymentMethod = {
  /** Saved Stripe v2 payment method. */
  type: "stripe_connect";
  /** Stripe payment method identifier. */
  payment_method_id?: string;
  /** Last 4 digits of the card when available. */
  last4?: string;
  /** Card brand label from Stripe (e.g., visa, mastercard). */
  card_brand?: string;
  /** Optional expiry month for saved-card display. */
  expiration_month?: number;
  /** Optional expiry year for saved-card display. */
  expiration_year?: number;
};

export type PaymentMethod =
  | CardPaymentMethod
  | PurchaseOrderPaymentMethod
  | AchPaymentMethod
  | StripeConnectPaymentMethod;
